spring:
  datasource:
    test:
      url: jdbc:postgresql://localhost:5432/test?escapeSyntaxCallMode=callIfNoReturn&reWriteBatchedInserts=true
      username: test
      password: test
      hikari:
        connectionTimeout: 30000 #30s
        idleTimeout: 600000 #10 minutes
        maxLifetime: 1800000 #30 minutes
        minimumIdle: 10
        maximumPoolSize: 50
      jpa:
        timeout: 300 #300s
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        generate-ddl: false
        properties:
          hibernate:
            batch_size: 15
            generate_statistics: false
          ddl-auto: none